'use client'
import './globals.css'
import { useState } from 'react';
import {
  AppShell,
  Navbar,
  Header,
  Footer,
  Aside,
  Text,
  MediaQuery,
  Burger,
  useMantineTheme,
} from '@mantine/core';
import HeroImageBackground from './hero';
import FooterLinks from './footerLinks';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  const [opened, setOpened] = useState(false);
  const theme = useMantineTheme();
  return (
    <html lang="en">
      <body style={{ backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0], }}>
        {/* <AppShell
          styles={{
            main: {
              // background: theme.colors.dark[8] ,
              background: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0],
            },
          }}
          // navbarOffsetBreakpoint="sm"
          // asideOffsetBreakpoint="sm"
          // navbar={
          //   <Navbar p="md" hiddenBreakpoint="sm" hidden={!opened} width={{ sm: 200, lg: 300 }}>
          //     <Text>Application navbar</Text>
          //   </Navbar>
          // }
          // aside={
          //   <MediaQuery smallerThan="sm" styles={{ display: 'none' }}>
          //     <Aside p="md" hiddenBreakpoint="sm" width={{ sm: 200, lg: 300 }}>
          //       <Text>Application sidebar</Text>
          //     </Aside>
          //   </MediaQuery>
          // }
          // footer={
          //   <Footer height={60} p="md" color={theme.colors.dark[8]}>
          //     Application footer
          //   </Footer>
          // }
          header={
            <Header height={{ base: 50, md: 70 }} p="md">
              <div style={{ display: 'flex', alignItems: 'center', height: '100%' }}>
                <MediaQuery largerThan="sm" styles={{ display: 'none' }}>
                  <Burger
                    opened={opened}
                    onClick={() => setOpened((o) => !o)}
                    size="sm"
                    color={theme.colors.gray[6]}
                    mr="xl"
                  />
                </MediaQuery>

                <Text>Application header</Text>
              </div>
            </Header>
          }
        > */}
        {children}

        {/* </AppShell> */}
        {/* <FooterLinks data={mockData.data} /> */}

      </body>
    </html>
  )
}
